-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 27-Maio-2016 às 22:23
-- Versão do servidor: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `sistema_blog`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `posts`
--

CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Content` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Author` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=139 ;

--
-- Extraindo dados da tabela `posts`
--

INSERT INTO `posts` (`id`, `Title`, `Content`, `Author`, `Date`) VALUES
(2, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Luiz Felipe', '2016-05-04'),
(6, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Rafael lima', '2016-05-11'),
(7, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Ana Costa', '2016-05-13'),
(9, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Marcelo Dias', '2016-05-18'),
(10, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Bruna Sousa', '2016-05-13'),
(11, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Rafael lima', '2016-05-19'),
(12, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Bruna Sousa', '2016-05-04'),
(13, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Ana Costa', '2016-05-20'),
(14, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Rafael lima', '2016-05-14'),
(15, 'Brasileirão teve quatro bons jogos na terceira rodada\n', 'Começou pela manhã com um 3 a 0 do Corinthians sobre a Ponte Preta e acabou à noite com outro 3 a 0 do Grêmio sobre o Atlético Mineiro, com a diferença importante de que o jogo matinal foi em Itaquera e o noturno no Horto.\n', 'Ana Costa', '2016-05-16'),
(16, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Ana Costa', '2016-05-19'),
(17, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Rafael lima', '2016-05-12'),
(18, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Rafael lima', '2016-05-20'),
(19, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Bruna Sousa', '2016-05-12'),
(20, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens. Estes blogs são uma excelente fonte de informação para quem pretende visitar um local mas não tem referências ou quer  pegar algumas dicas ', 'Luiz Felipe', '2016-05-16'),
(21, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens. Estes blogs são uma excelente fonte de informação para quem pretende visitar um local mas não tem referências ou quer  pegar algumas dicas ', 'Luiz Felipe', '2016-05-20'),
(22, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Ana Costa', '2016-05-05'),
(29, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Rafael lima', '2016-05-04'),
(30, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Bruna Sousa', '2016-05-03'),
(31, '40 BLOGS SOBRE VIAGENS E TURISMO QUE VOCÊ PRECISA CONHECER\n', 'Está cada dia mais comum, pessoas apaixonadas por viagens criarem blogs para registrar em detalhes as suas viagens.', 'Ana Costa', '2016-05-01'),
(32, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Luiz Felipe', '2016-05-05'),
(33, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Ana Costa', '2016-05-06'),
(34, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Bruna Sousa', '2016-05-10'),
(35, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Ana Costa', '2016-05-05'),
(36, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo. Como você pode ver logo abaixo deste parágrafo, o anúncio do smartphone vai ter uma forte relação com o nú', 'Luiz Felipe', '2016-05-21'),
(37, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Ana Costa', '2016-05-23'),
(38, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Luiz Felipe', '2016-05-21'),
(39, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Bruna Sousa', '2016-05-23'),
(40, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Bruna Sousa', '2016-05-02'),
(41, 'ASUS Zenfone 3 pode chegar com 6 GB de memória RAM; será?\n', 'Nesta semana, uma imagem teaser  do aparelho foi publicada na imprensa internacional e mostra que podemos ter uma grande surpresa com o dispositivo', 'Luiz Felipe', '2016-05-22'),
(42, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Ana Costa', '2016-05-24'),
(43, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Luiz Felipe', '2016-05-24'),
(44, 'Samsung está desenvolvendo novo display voltado para a realidade virtual', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Ana Costa', '2016-05-19'),
(45, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Luiz Felipe', '2016-05-04'),
(46, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Ana Costa', '2016-05-21'),
(47, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Bruna Sousa', '2016-05-22'),
(48, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Bruna Sousa', '2016-05-17'),
(49, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Ana Costa', '2016-05-16'),
(50, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Bruna Sousa', '2016-05-05'),
(51, 'Samsung está desenvolvendo novo display voltado para a realidade virtual\n', 'Para uma questão de comparação – e o motivo pelo qual esse protótipo da Samsung é realmente impressionante –, dispositivos como o Oculus Rift e HTC Vive trabalham com resolução bem mais baixa, 2160x1200 pixels. ', 'Rafael Lima', '2016-05-13'),
(52, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Luiz Felipe', '2016-05-04'),
(53, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2016-05-09'),
(54, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2016-05-22'),
(55, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2016-05-11'),
(56, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2016-05-11'),
(57, 'OnePlus 3 será anunciado no dia 14 de junho', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2016-05-25'),
(58, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2016-05-11'),
(59, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2016-05-09'),
(60, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2016-05-09'),
(61, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2016-05-24'),
(62, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(63, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2003-03-20'),
(64, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2016-05-10'),
(65, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(66, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2014-02-23'),
(67, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(68, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2014-02-23'),
(69, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(70, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2014-02-23'),
(71, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(72, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Ana Costa', '2014-02-23'),
(73, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(74, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(75, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(76, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(77, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(78, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(79, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(80, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(81, 'OnePlus 3 será anunciado no dia 14 de junho', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2016-05-25'),
(82, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Luiz Felipe', '2016-03-30'),
(83, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(84, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(85, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2014-02-23'),
(86, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Luiz Felipe', '2014-02-23'),
(87, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Rafael Lima', '2016-03-30'),
(88, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Luiz Felipe', '2016-03-30'),
(89, 'OnePlus 3 será anunciado no dia 14 de junho\n', 'Nesta semana vazaram as possíveis especificações do aparelho, que é cogitado a chegar ao mercado com configurações bem interessantes — lembrando que há rumores que apontam para versões com até 6 GB de memória RAM.', 'Bruna Sousa', '2014-02-23'),
(90, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Luiz Felipe', '2014-02-23'),
(91, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'receitaVocê está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2014-02-23'),
(92, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2014-02-23'),
(93, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Luiz Felipe', '2014-02-23'),
(94, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2014-02-23'),
(95, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2016-03-30'),
(96, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Luiz Felipe', '2014-02-23'),
(97, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2014-02-23'),
(98, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Luiz Felipe', '2014-02-23'),
(99, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Luiz Felipe', '2014-02-23'),
(100, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2016-03-30'),
(101, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2016-03-30'),
(102, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2014-02-23'),
(103, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2014-02-23'),
(104, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2014-02-23'),
(105, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2016-03-30'),
(106, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2014-02-23'),
(107, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Luiz Felipe', '2016-03-30'),
(108, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2014-02-23'),
(109, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2016-03-30'),
(110, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil\n', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Bruna Sousa', '2016-03-30'),
(135, 'Os 5 personagens da ficção que seriam melhores presidentes do Brasil', 'Você está insatisfeito com a situação política e econômica do nosso país? Também tem a impressão de que o Brasil está sendo governado por pessoas que se dizem competentes, mas não conseguem gerenciar corretamente a nossa maravilhosa pátria?', 'Rafael Lima', '2014-02-23');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
